sudo: enabled
dist: xenial
language: generic
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="DIST=16 BVER=1_70_0"
    - os: linux
      env:
        - MATRIX_EVAL="DIST=18 BVER=1_70_0"
    - os: linux
      env:
        - MATRIX_EVAL="DIST=18 BVER=1_71_0"

before_install:
    - docker --version
    - eval "${MATRIX_EVAL}"
    - env

script:
  # build aliases
  - echo "${DOCKER_PASSWORD}" | docker login -u romange --password-stdin
  - |
    set -e
    push() {  #function definition must be multi-line
      docker push $1
    }

    pull() {
      docker pull $1
    }

    build() {
      set -e
      docker build -t $1 --build-arg DIST=${DIST} \
        --build-arg BOOST_VERSION=${BVER} .
    }

    deploy() {
      set -e
      IMAGE=romange/$1:$2
      date
      cd $1 && build $IMAGE && push $IMAGE && cd ..
      date
    }

    deploy ugcc ${DIST}
    deploy boost-dev ${DIST}_${BVER}
    deploy boost-prod ${DIST}_${BVER}
  - echo "Success"
