sudo: enabled
dist: xenial
language: cpp
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="DIST=16 BVER=1_70_0"
    - os: linux
      env:
        - MATRIX_EVAL="DIST=18 BVER=1_70_0"
    - os: linux
      env:
        - MATRIX_EVAL="DIST=18 BVER=1_71_0"

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u romange --password-stdin
    - eval "${MATRIX_EVAL}"

script:
  # build aliases
  - |
    set -e
    push() {  #function definition must be multi-line
      docker push $1
    }

    pull() {
      docker pull $1
    }

    build() {
      pull $1 && docker build --cache-from $1 -t $1 --build-arg DIST=${DIST} \
        --build-arg BOOST_VERSION=${BVER} .
    }

    deploy() {
      IMAGE=romange/$1:${DIST}_${BVER}
      date
      cd $1 && build $IMAGE && push $IMAGE && cd ..
      date
    }
    deploy ugcc
    deploy boost-dev
    deploy boost-prod
  - echo "Success"
