#cloud-config

package_update: true
package_upgrade: true

groups:
  - docker

users:
 - default  # Keeps the default ubuntu user intact
 - name: dev
   sudo: ALL=(ALL) NOPASSWD:ALL
   groups: adm, docker
   shell: /bin/bash
   ssh_authorized_keys:
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCano8DfBycFQ/2OxszQ5ZcnHpodZBI4XGsiTK+bw/RxGgwdL6V3/de53DtjZNCltCgfU04fw8wntm2SJ/PyguN8O/Kj3qSD9QHI04CBe2P/Z+GOfJUo528ocIj2PnWHTV8zs5XZVyRaZCLyNfiKTnkfY7EoTHDVJcuUE669v9Q5FDPVBp0eUMGW49Gw1i1z6dXJiv7pfEGyKCcMuGiPnCB357XsuxKzEThazlpuRFWXPqilBOI8hSapMd8G0TXU9xhGNNzpBdrZg6DFvoXX2JChD9sOBNumS0FMv0BEBbZeonMzMHoVU6mMfFMnYAEMJesCXK12vcr440HM8sXC20H

packages: [ ack-grep, automake, binutils, bzip2, ca-certificates, ccache, curl, doxygen, htop,
  iftop, gdb, graphviz, g++, libunwind-dev, linux-tools-common, ninja-build, libbz2-dev, git,
  make, autoconf, libtool, libssl-dev, libxml2-dev, golang, docker.io, python3-setuptools, cmake,
  libhugetlbfs-bin, awscli, mlocate, parallel, python3-pip, vim,
  vim-gui-common, net-tools, libncurses5-dev, unzip, wget, zip]
