#cloud-config
package_update: true
package_upgrade: true

groups:
- docker
users:
- default
- name: dev
  sudo: ALL=(ALL) NOPASSWD:ALL
  groups: adm, docker
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCano8DfBycFQ/2OxszQ5ZcnHpodZBI4XGsiTK+bw/RxGgwdL6V3/de53DtjZNCltCgfU04fw8wntm2SJ/PyguN8O/Kj3qSD9QHI04CBe2P/Z+GOfJUo528ocIj2PnWHTV8zs5XZVyRaZCLyNfiKTnkfY7EoTHDVJcuUE669v9Q5FDPVBp0eUMGW49Gw1i1z6dXJiv7pfEGyKCcMuGiPnCB357XsuxKzEThazlpuRFWXPqilBOI8hSapMd8G0TXU9xhGNNzpBdrZg6DFvoXX2JChD9sOBNumS0FMv0BEBbZeonMzMHoVU6mMfFMnYAEMJesCXK12vcr440HM8sXC20H
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2IaMLRNXtpIQ22pEwaQARoVnbI60qtKBH/O7YUQOWeVsEVM4K+9jx1BOzTHox1vMsV3PHGtkz5UtGaAMfgK8wy1sbC1tXZjPArUVfqgp8/wAe1Buyihs6FR3kWMTevbrBCvucvgYqFUrENAu0A8ixxoOmFrLN+ix470KyHCCQfhw8aVXx8CIHO0L2aukvLwMZ1SEsIolOHu+yniAVTp/sGXDIXLOZe/vjMutV8+iEw2Vbm+pXF/nZzNgBb/i5H8WgcnS/iWYeQd/UeWo5f4mA6aMtZ5EunyC/gM7rwIGcujpx0QeTXOqCy7VD2G+qFFOjBnZaCpJ1MNhHGfwWihLvinHm0hJrxuvxBItpmsUI60qv4uIsIiSArcph0yKvyam70YIEhMj//1tyNgSqRyHVt5FNeZ3PICpi71kHLOv8qHJWIWZ6voqM8XyvyiUEiqFBbvUxYXIhy2/SrYhy11embO1TkcOpUFbjgfC3VNmbdpVUqyMx9oxFJ8zfGOYgU10=
runcmd:
- systemctl stop apparmor
- systemctl disable apparmor
- modprobe -rv ip_tables

packages:
- acl
- automake
- autoconf
- binutils
- bison
- bzip2
- ca-certificates
- ccache
- cmake-curses-gui
- chrony
- cloc
- curl
- dkms
- doxygen
- htop
- iftop
- iotop
- flex
- gdb
- graphviz
- git
- golang
- libelf-dev
- libtool
- make
- mlocate
- ninja-build
- npm
- parallel
- podman
- runc
- sysstat
- tcptrace
- python3-pip
- python3-setuptools
- vim
- unzip
- wget
- zip
- ack-grep
- cmake
- g++
- libunwind-dev
- linux-tools-generic
- libbz2-dev
- docker.io
- libhugetlbfs-bin
- libncurses5-dev
- libssl-dev
- libxml2-dev
- vim-gui-common
- net-tools
- libboost-fiber-dev
- iperf3
%{if os == "ubuntu"}
- linux-tools-generic
%{endif}
